### PR TITLE
cspp mixer support

### PR DESCRIPTION
**Pull request by C-ollins**
Requires https://github.com/planetdecred/dcrlibwallet/pull/150
- Added account mixer page, an option to create mixed & change accounts if not done already and a switch to toggle account mixer.
- Generating an address for the mixed account & sending funds from the change account are disabled.
- Account mixer is disabled for watch only wallets.

| | |
|-|-|

### CODE REVIEW

**Comment by svitekpavel** [comment]
@C-ollins would it be possible to have "mix tx by default" setting in the app? So every transaction one send would be mixed by default.

**Comment by C-ollins** [comment]
@svitekpavel I don’t get what ‘mixed by default’ means but you can send transactions using mixed funds when you use the designated ‘mixed account’ and you can also send the change from your transactions to the designated ‘unmixed account’ for mixing.

**Comment by svitekpavel** [comment]
> @svitekpavel I don’t get what ‘mixed by default’ means but you can send transactions using mixed funds when you use the designated ‘mixed account’ and you can also send the change from your transactions to the designated ‘unmixed account’ for mixing.

Mixer support is not yet in Decrediton so I don't know what will be the UX there, but the point I'm trying to make is to allow users to have "privacy by default" when they transact with other users.

**Comment by C-ollins** [comment]
@svitekpavel the UX is still a work in progress but currently a user can set an account as ‘mixed account’ and any transaction created from that account would sent be using privacy.

**Comment by svitekpavel** [comment]
Does user need to send money first to his "mixed account" in order to send mixed tx to somebody else, or do I simply choose "from mixed account" and the money from normal wallet will be "pulled" automatically?

**Comment by C-ollins** [comment]
The process isn’t streamlined currently. The user sends funds to a designated ‘unmixed account’, the cspp mixer runs in background and will mix any funds found in the unmixed account and put them in the mixed account. The user can now spend the funds from the mixed account.

**Comment by svitekpavel** [comment]
Thank you for explanation. Appreciated.

**Pull request closed without merging**
