### PR TITLE
Update French translation (#600 and #604)

### PR DESCRIPTION
**Pull request by jdambron**
Update French translation for PRs #600 and #604

### CODE REVIEW

**Comment by jdambron** [comment]
@dreacot after 5 months, probably.
I will have a look when possible.

**Comment by dreacot** [comment]
Thanks, awaiting your feedback

**Comment by jdambron** [comment]
@dreacot it should be good now.
I merged master and added all missing translations since this PR.

**Comment by dreacot** [comment]
@jdambron thanks a lot👌🏽, before would probably merge this last, for the last minute PRs coming up

**Review by dreacot — APPROVED** [review]

**Pull request merged**
